config/routes.rb
SampleApp::Application.routes.draw do
  get "password_resets/new"
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@micropost = current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About DebtHacker</h1>
<p>
	DebtHacker is a feature that could be layered onto existing repayment plan calculators (of which we’ve found quite a few great ones including Simple Tuition’s http://paybacksmarter.com/). After answering a few simple questions such as (but not necessarily these questions) “Did you graduate?” or “Are you currently employed?” we would generate a “Hack Profile” that would give tailored information on repayment plans to the individual, making sure that, for example, those who have risk factors for delinquency, would have easy access to information on deferment, forbearance, and income-driven plans.
</p>

<p>
	We picture this being the first step in trying to provide more contextualized information about repayment to students who are confused by the many repayment options they have to choose from, especially those borrowers most at risk of default. We should be able to get a prototype of this done by January 15th. We are still thinking of how to provide better context to loan repayment depending on major life milestones, something that we’ve seen many calculators try and do but fall short, but that would be a feature of DebtHacker 2.0. This idea is simple but still would be valuable to borrowers, and is something we haven’t seen during our research to see what other kinds of online repayment tools already exist.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at
	<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
Here's where we can have some useful help content if it's applicable. 
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

	<h3>We've created a custom profile based on your answers.</h3>
	<p>Extra explanation can go here, particularly if it helps make the demo more cohesive. We can also just put the profile itself on this page, but I thought an interstitial page like this one would make a better story.</p>
	<%= link_to "View Profile", current_user, class: "btn btn-large btn-primary" %>
	<%= link_to "Review Questions", edit_user_path(current_user), class: "btn btn-large" %>

<% else %>

	<div class="center hero-uint">
	  <h1>DebtHacker <br><small>Understand your repayment options.</small></h1>
	  <%= link_to "Get Started", signup_path, class: "btn btn-large btn-primary" %>
	  <p><br>Already have an account? <%= link_to "Sign in", signin_path %></p>
	</div>

<% end %>